# Generated by Django 3.1.12 on 2026-01-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('lugar', models.CharField(max_length=200)),
                ('organizador', models.CharField(max_length=100)),
                ('costo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
            ],
        ),
    ]
