# Generated by Django 3.1.12 on 2026-01-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('hotel', 'Hotel'), ('restaurante', 'Restaurante'), ('tour', 'Tour Guiado'), ('transporte', 'Transporte')], max_length=50)),
                ('descripcion', models.TextField()),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('precio_rango', models.CharField(max_length=100)),
                ('calificacion', models.FloatField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/')),
            ],
        ),
    ]
