# Generated by Django 3.1.12 on 2026-01-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('natural', 'Atracción Natural'), ('cultural', 'Sitio Cultural'), ('historico', 'Sitio Histórico'), ('gastronomico', 'Gastronomía')], max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='destinos/')),
                ('horario', models.CharField(max_length=100)),
                ('precio_aprox', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
